version: '3.3'

services:
  web3d-client:
    build: ./client
    container_name: web3d-client
    ports:
      - "80:80"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web3d-server:
    build: ./server
    container_name: web3d-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=220.85.41.214
      - DB_PORT=3306
      - DB_NAME=twdb
      - DB_USER=twuser
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
